theme: jekyll-theme-minimal
title: Magentron's documentation
description: Magentron's documentation
logo: https://www.magentron.com/skin/frontend/magentron/default/images/xmagentron-logo.png,Mce.vuCu7ji9kA.png.pagespeed.ic.0I1sf8o82P.webp
